---
title: "Untitled"
author: "Shyam BV"
date: "April 8, 2017"
output: html_document
---

```{r setup, include=FALSE}
if(!require("matlib", character.only = TRUE, quietly = TRUE)) {
  install.packages("matlib")
  library("matlib", character.only = TRUE)
}

if(!require("rgl", character.only = TRUE, quietly = TRUE)) {
  install.packages("rgl")
  library("rgl", character.only = TRUE)
}

if(!require("Matrix", character.only = TRUE, quietly = TRUE)) {
  install.packages("Matrix")
  library("Matrix", character.only = TRUE)
}


```


```{r}

#A <- matrix(c(0,1/2,1/2,0,0,0,0,0,0,0,0,0,1/3,1/3,0,0,1/3,0,0,0,0,0,1/2,1/2,0,0,0,1/2,0,1/2,0,0,0,1,0,0),ncol=6)
A <- matrix(c(0,1/2,1/2,0,0,0,0,0,0,0,0,0,1/3,1/3,0,0,1/3,0,0,0,0,0,1/2,1/2,0,0,0,1/2,0,1/2,0,0,0,1,0,0),ncol=6)


r <- matrix(c(1/6,1/6,1/6,1/6,1/6,1/6),ncol=1)

det(A)


#eigen(A %*% A %*% A)

(A %*% A %*% A %*% A) %*% r
(A %*% A %*% A %*% A %*% A %*% A %*% A%*% A%*% A%*% A%*% A%*% A%*% A%*% A%*% A %*% A%*% A%*% A%*% A%*% A%*% A%*% A%*% A %*% A %*% A %*% A %*% A %*% A %*% A%*% A%*% A%*% A%*% A%*% A%*% A%*% A%*% A %*% A) %*% r

eigen(A)

B = 0.85*A+(.15/4)

eigen(B)




```




a



```{r}

r <- matrix(c(1/5,1/5,1/5,1/5,1/5),ncol=1)

H <- matrix(c(0,1,0,0,0,0,0,0,0,1,1/4,1/4,0,1/4,1/4,0,0,1/2,0,1/2,0,0,0,1,0), ncol = 5)

H %*%r 

r1 =matrix(c(1/20,5/20,1/10,5/20,7/20),ncol=1)

r2 =matrix(c(1/40,3/40,5/40,15/40,16/40),ncol=1)

r3 = (H %*% H %*% H) %*%r 
sum(r3)

eigen(H)


H %*%r 


```
```{r}
H <- matrix(c(.6,.15,.4,.85), ncol=2)

r = matrix(c(.1,.9),nrow =1)

2 - (r %*% (H^2))
```
```{r}
H <- matrix(c(.5,.5,0,.5,0,.5,0,0,1), ncol=3)

r = matrix(c(1/3,1/3,1/3),ncol =1)

((H %*% H) %*% r)

I = matrix(c(1,1,1,1,1,1,1,1,1),ncol =3)

d =.8
d*H+((1-d)/3)
B = d*H+((1-d)*(I/3))
B

eigen(B)


```
```{r}

A <- matrix(c(0,1/2,1/2,0,0,0,0,0,0,0,0,0,1/3,1/3,0,0,1/3,0,0,0,0,0,1/2,1/2,0,0,0,1/2,0,1/2,0,0,0,1,0,0),ncol=6)

# Introduce decay d = 0.85

d <- 0.85

B <- 0.85*A + (0.15/6)

matrixPower <- function(A, power, B){
  if(power == 1){
    return(A)
  }else{
    return(matrixPower(A %*% B, power - 1, B))
  }
}

r <- matrix(c(1/6,1/6,1/6,1/6,1/6,1/6),nrow=6)

k <- 500

rk <- matrixPower(B,k,B) %*% r

rk


sum(eigen(B)$values)

# Need to scale the Eigenvectors, I just divided the vectors to get my scale.

(rk / eigen(B)$vectors[,1]) * eigen(B)$vectors[,1]



```

