---
title: "Movie Recommendation"
author: "Shyam BV"
date: "June 7, 2017"
output: html_document
---

This system recommends movies to different users

```{r}
if(!require("dplyr", character.only = TRUE, quietly = TRUE)) {
  install.packages("dplyr")
  library("dplyr", character.only = TRUE)
}

if(!require("tidyr", character.only = TRUE, quietly = TRUE)) {
  install.packages("tidyr")
  library("tidyr", character.only = TRUE)
}

if(!require("ggplot2", character.only = TRUE, quietly = TRUE)) {
  install.packages("ggplot2")
  library("ggplot2", character.only = TRUE)
}

if(!require("Metrics", character.only = TRUE, quietly = TRUE)) {
  install.packages("Metrics")
  library("Metrics", character.only = TRUE)
}

```



```{r}
ratings_na <- read.csv("data/ratings.csv",sep=",",header=TRUE) %>% select(-timestamp) %>% spread(movieId,rating) 

ratings <- ratings_na %>% mutate_each(funs(replace(.,is.na(.),0)),c(1:ncol(.)) )

ratings_bak <- ratings
ratings <- ratings_bak
```

Separate between training and test dataset


```{r}
test_rows <- sample(nrow(ratings),nrow(ratings)*.1)

test_cols <- sample(ncol(ratings),ncol(ratings)*.1)

(test = ratings[test_rows,test_cols])

ratings[test_rows,] %>% select(userId)

(test <- bind_cols(ratings[test_rows,] %>% select(userId),test))

ratings[test_rows,test_cols] =0

```


Raw average of training dataset

```{r}

nzmean <- function(x) {
    if (all(x==0)) 0 else mean(x[x!=0])
}

#Row means - User means
training_mean_rows = ratings %>% select(-userId) %>%  apply(1,nzmean)
(training_mean = mean(training_mean_rows))

ratings <- bind_cols(data.frame(training_mean_rows),ratings)


#Column means - Movies means
training_mean_cols = ratings %>%  apply(2,nzmean)
test_test = training_mean_cols

head(training_mean_cols)
head(colMeans(ratings_na,na.rm = TRUE))

test_test <- mean(as.matrix(),na.rm = TRUE)

head(ratings_na)

 mean(ratings_na,na.rm = TRUE)

(test_test[-c(1,2)])


(training_mean = mean(training_mean_cols))

ratings <- bind_cols(data.frame(training_mean_rows),ratings)



(test_mean_rows = mean(test %>% select(-userId) %>%  apply(1,nzmean)))
test_mean = mean(test_mean_rows)



```

#RMSE

```{r}

nzrmse <- function(x,type) {
  
  if (type=='training'){
    if (all(x==0)) 0 else rmse(x[x!=0],training_mean)
  }
  else if(type=='test'){
        if (all(x==0)) 0 else rmse(x[x!=0],test_mean)
  }
    }

#Training
(final_rmse = sum(ratings %>% select(-userId) %>%  apply(1,nzrmse,type='training')))


#Test
(test_rmse = sum(test %>% select(-userId) %>%  apply(1,nzrmse,type='test')))

```

#Calculate User bias

that line user value - mean value

that line item value - mean value


```{r}

```

