---
title: "Practiece - Subspaces"
author: "Shyam BV"
date: "February 25, 2017"
output: html_document
---

```{r setup, include=FALSE}
if(!require("matlib", character.only = TRUE, quietly = TRUE)) {
  install.packages("matlib")
  library("matlib", character.only = TRUE)
}

if(!require("rgl", character.only = TRUE, quietly = TRUE)) {
  install.packages("rgl")
  library("rgl", character.only = TRUE)
}

if(!require("Matrix", character.only = TRUE, quietly = TRUE)) {
  install.packages("Matrix")
  library("Matrix", character.only = TRUE)

}

if(!require("pracma", character.only = TRUE, quietly = TRUE)) {
  install.packages("pracma")
  library("pracma", character.only = TRUE)
}


```



```{r}

A_3x5 = matrix(c(1,1,0,2,2,0,2,3,1,4,6,2,6,9,3),nrow=3,ncol=5)

A_3x3
echelon(A_3x3)

gaussianElimination(A_3x3)


nullspace(A_3x3)

rref(A_3x3)


A_2x3 = matrix(c(-1,-2,3,6,5,10),nrow=2,ncol=3)
A_2x3

nullspace(A_2x3)

A_4x4 = matrix(c(1,-1,0,0,-1,2,-1,0,0,-1,2,-1,0,0,-1,1),nrow=4,ncol=4)

A_4x4
rref(A_4x4)
gaussianElimination(A_4x4)

SVD(A_4x4)

A_3x3 = matrix(c(1,0,0,2,4,0,3,5,6),nrow=3,ncol=3)
A_3x3
test<- SVD(A_3x3)

(test$V %*% test$d) %*% t(test$V)

t(test$V)

inv(test$V)


#########


A = matrix(c(2,-1,2,1),nrow=2,ncol=2)
test = SVD(A)
test
A
eigen(A)
gaussianElimination(A)

(test$U %*% diag(test$d)) %*% t(test$V)

t(A) %*% A

test$d
diag(test$d)

D <- diag(test$d)
s$u %*% D %*% t(s$v)


A = matrix(c(1,3,7,-2,0,5),nrow=3,ncol=2)

A
t(A)

inv(A)



### Square



A = matrix(c(2,1,2,1),nrow=2,ncol=2)
A = matrix(c(1,-1,0,5,2,0,1,4,3,1,-2,-2,4,3,1,-3),nrow=4,ncol=4)
A = matrix(c(1,1,1,2,1,3),nrow=2,ncol=3)
A = matrix(c(1,7,3,7,4,-5,3,-5,6),nrow=3,ncol=3)

A
eigen(A)
SVD(A)
gaussianElimination(A)

#Non square

A = matrix(c(1,1,1,2,1,3),nrow=2,ncol=3)
A
A %*% t(A)
t(A) %*% A
eigen(test)

SVD(A)
gaussianElimination(A)


SVD(A)$U
t(SVD(A)$U)
inv(SVD(A)$U)


```

